nicfv/npm

.github/workflows/publish.yml
.github/workflows/run
smath/CHANGELOG.md
smath/package.json
smath/src/Interpolator.ts
smath/src/index.ts

- Basic interpolation functions
- Better error catching in runner file
- Generate documentation with typedoc
- Add homepage

Release v0.0.2

---

.github/workflows/run
smath/package.json
viridis/CHANGELOG.md
viridis/README.md
viridis/package.json
viridis/src/Color.ts
viridis/src/Gradient.ts
viridis/src/Palette.ts

- Update typedoc dependency
- More robust CI script
- Color gradients
- Default color palettes
- Generate gradient CSS
- Get colors from hex string

Release Viridis v0.0.3

---

viridis/CHANGELOG.md
viridis/README.md
viridis/package.json
viridis/src/index.ts

- Actually export color palettes
- Update tagline

Viridis v0.0.4

---

viridis/CHANGELOG.md
viridis/README.md
viridis/package.json
viridis/src/Gradient.ts

Viridis v1.0.2: Package updates and public gradient color array

---

viridis/CHANGELOG.md
viridis/README.md
viridis/package.json
viridis/src/Gradient.ts

Viridis v1.0.3

---

datafit/CHANGELOG.md
datafit/README.md
datafit/package.json
datafit/src/CurveFit.ts
datafit/src/types.ts

- Randomly mutate sets of parameters
- Allow single or multi-variable functions

Datafit - Genetic algorithm

---

datafit/README.md
datafit/src/lib.ts

- First full release of datafit
- Includes all relevant documentation
- Should be bug free!
- Closes #36

Datafit v1.0.0

---

datafit/CHANGELOG.md
datafit/package.json

I forgot to update the changelog and `package.json`. This PR will actually close #36 and fix #39

Datafit v1.0.0 (actual)

---

datafit/CHANGELOG.md
datafit/package.json
datafit/tsconfig.json

- Reduce compiler library version

Datafit v1.0.2

---

datafit/CHANGELOG.md
datafit/package.json
datafit/src/lib.ts
datafit/src/types.ts

Datafit v1.0.3

---

.github/workflows/template.md
smath/CHANGELOG.md
smath/README.md
smath/package.json
smath/src/index.ts

- Add linspace and logspace functions
- Update getting started documentation

Smath v1.1.5

---

datafit/CHANGELOG.md
datafit/README.md
datafit/package.json

Datafit v1.1.1

---

smath/CHANGELOG.md
smath/package.json
viridis/CHANGELOG.md
viridis/package.json

Update package scripts

---

qnt/CHANGELOG.md
qnt/README.md
qnt/package.json
qnt/src/index.ts
qnt/tsconfig.json

Qnt v0.0.1

---

.github/workflows/home/index.html
.github/workflows/home/index.js
.github/workflows/home/main.css
.github/workflows/run
.github/workflows/template.md

Add homepage

---

.github/workflows/template.md
datafit/CHANGELOG.md
datafit/README.md
datafit/examples/package.json
datafit/examples/simple.ts
datafit/examples/singlevariable.ts
datafit/package.json
datafit/src/lib.ts
datafit/src/types.ts

- Add YouTube link
- Update Summary schema
- Update examples

Datafit v1.2.0

---

datafit/CHANGELOG.md
datafit/README.md
datafit/examples/package.json
datafit/examples/singlevariable.ts
datafit/package.json
datafit/src/lib.ts
datafit/src/types.ts

- Normalize max deviation
- Rename variable in summary
- Update examples/outputs

Datafit v1.3.0

---

.github/workflows/template.md
datafit/CHANGELOG.md
datafit/examples/package.json
datafit/package.json
exray/CHANGELOG.md
exray/examples/package.json
exray/package.json
smath/CHANGELOG.md
smath/examples/package.json
smath/package.json
viridis/CHANGELOG.md
viridis/examples/package.json
viridis/package.json

Fix broken home link

---

datafit/CHANGELOG.md
datafit/examples/package.json
datafit/package.json
datafit/tsconfig.json
exray/CHANGELOG.md
exray/examples/package.json
exray/package.json
exray/tsconfig.json
viridis/CHANGELOG.md
viridis/examples/package.json
viridis/package.json
viridis/tsconfig.json

I wish there was a way to have a base tsconfig! I've tried it, but the paths (e.g. outDir, include) would need to be overridden for each tsconfig.

Generate type declarations

---

exray/CHANGELOG.md
exray/examples/4-Custom-Message.md
exray/examples/package.json
exray/package.json
exray/src/index.ts
exray/test/index.ts

- Show which test id failed
- Improve on some of the default messages
- Add meta-tests (test the tester!)

Exray v1.0.0

---

smath/CHANGELOG.md
smath/examples/package.json
smath/package.json

- Add unit tests: #64
- Install exray devDependency

smath v1.3.4

---

README.md
exray/CHANGELOG.md
exray/examples/package.json
exray/package.json
exray/src/test.ts
smath/CHANGELOG.md
smath/examples/package.json
smath/package.json
smath/src/test.ts

- Add ci badge on main readme
- Test script consolidation

exray v1.0.1 and smath v1.3.5

---

README.md
datafit/CHANGELOG.md
datafit/examples/package.json
datafit/package.json
datafit/src/test.ts
datafit/src/types.ts
exray/CHANGELOG.md
exray/README.md
exray/examples/package.json
exray/package.json
smath/CHANGELOG.md
smath/README.md
smath/examples/package.json
smath/package.json
smath/src/bin.ts
smath/src/index.ts
smath/src/test.ts
viridis/CHANGELOG.md
viridis/examples/package.json
viridis/package.json
viridis/src/Color.ts
viridis/src/test.ts

- Closes #64
- Closes #66
- Closes #81

Weekend updates

---

smath/CHANGELOG.md
smath/examples/package.json
smath/package.json
smath/src/bin.ts
smath/src/index.ts
smath/src/test.ts

- Add calc functions
- Add tests for standard deviation

Smath v1.6.0

---

smath/CHANGELOG.md
smath/examples/package.json
smath/package.json
smath/src/bin.ts
smath/src/index.ts
smath/src/test.ts

Smath v1.6.1

---

datafit/CHANGELOG.md
datafit/examples/package.json
datafit/package.json
datafit/src/lib.ts
datafit/src/test.ts
datafit/src/types.ts

- Use normal distribution for mutations instead of uniform distribution

Datafit v1.4.2

---

dimensional/CHANGELOG.md
dimensional/README.md
dimensional/examples/package.json
dimensional/package.json
dimensional/src/index.ts
dimensional/src/test.ts
dimensional/tsconfig.json

This package should include 3 main features:
- Dimensional analysis
- Quantity mathematics
- Unit conversions
It will be the base for the future "engineers" package.

Dimensional v0.0.0

---

smath/CHANGELOG.md
smath/examples/package.json
smath/package.json
smath/src/index.ts

- `abstract class` -->> `namespace`
- Dependency updates (address issues in #99)

SMath v1.8.0

---

datafit/package.json
dimensional/package.json
exray/package.json
smath/package.json
viridis/package.json

Postpack was removing node_modules, effectively uninstalling all dependencies. Let's not do that.

Revert postpack script

---

package.json
typedoc.json

- Update typescript version to 5.6.2
- Update typedoc version to 0.26.7
- Add hyperlink to main website in footer

Documentation updates

---

.github/workflows/run
packages/datafit/CHANGELOG.md
packages/datafit/package.json
packages/smath/CHANGELOG.md
packages/smath/package.json
packages/t6/CHANGELOG.md
packages/t6/package.json
packages/viridis/CHANGELOG.md
packages/viridis/package.json

Provenance

---

.github/workflows/run
packages/datafit/CHANGELOG.md
packages/datafit/examples/package.json
packages/datafit/package.json
packages/smath/CHANGELOG.md
packages/smath/examples/package.json
packages/smath/package.json
packages/t6/CHANGELOG.md
packages/t6/examples/package.json
packages/t6/package.json
packages/viridis/CHANGELOG.md
packages/viridis/examples/package.json
packages/viridis/package.json

Forgot to update the example versions...

Provenance (fix)

---

packages/smath/CHANGELOG.md
packages/smath/examples/package.json
packages/smath/package.json
packages/t6/CHANGELOG.md
packages/t6/examples/package.json
packages/t6/package.json

I realize I probably could have done this at the same time as #129 , since `t6` is a `devDependency`. Oh well, try again next time.

Smath v1.9.2 & T6 v1.1.8

---

.github/workflows/scripts
CONTRIBUTING.md
README.md
packages/smath/CHANGELOG.md
packages/smath/examples/Deck Shuffler.md
packages/smath/examples/Deck Shuffler.mjs
packages/smath/package.json
packages/smath/src/index.ts
packages/smath/src/test.ts

+Shuffle
Also, test the publish feature: #136

SMath v1.10.0

---

.github/workflows/scripts
CONTRIBUTING.md
packages/psychart/CHANGELOG.md
packages/psychart/README.md
packages/psychart/example/Temp.md
packages/psychart/example/Temp.mjs
packages/psychart/package.json
packages/psychart/src/index.ts
packages/psychart/src/test.ts
packages/psychart/tsconfig.json

Bring Psychart into the mix! :)
https://github.com/nicfv/Psychart

Psychart 0.0.1

---

packages/psychart/CHANGELOG.md
packages/psychart/example/Blank Chart/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/index.ts

Psychart v0.1.1

---

packages/psychart/CHANGELOG.md
packages/psychart/package.json
packages/psychart/src/psychart.ts
packages/psychart/src/types.ts

- Independent axis intervals
- Units in axis tooltips

Psychart v0.2.1

---

packages/psychart/CHANGELOG.md
packages/psychart/example/Mollier Diagram/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/psychart.ts
packages/psychart/src/types.ts

Psychart v0.2.2

---

package.json
packages/psychart/CHANGELOG.md
packages/psychart/example/Plotting Data/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/psychart.ts
packages/psychart/src/types.ts

Psychart v0.3.1

---

packages/psychart/CHANGELOG.md
packages/psychart/example/Plotting Data/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/psychart.ts
packages/psychart/src/types.ts

Psychart interactive legend

---

packages/psychart/CHANGELOG.md
packages/psychart/README.md
packages/psychart/example/Plotting Data/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/psychart.ts
packages/psychart/src/psystate.ts
packages/psychart/src/test.ts
packages/psychart/src/types.ts
typedoc.json

- Closes #164 
- Closes #166 
- Closes #167

Psychart updates

---

packages/psychart/CHANGELOG.md
packages/psychart/package.json
packages/psychart/src/psychart.ts

- Add function to draw a line between 2 arbitrary points.

Psychart v0.4.2

---

packages/psychart/CHANGELOG.md
packages/psychart/package.json
packages/psychart/src/psychart.ts
packages/psychart/src/psystate.ts

psychart hotfix

---

packages/psychart/CHANGELOG.md
packages/psychart/package.json
packages/psychart/src/psychart.ts

psychart v0.4.4

---

packages/psychart/CHANGELOG.md
packages/psychart/example/Mollier Diagram/src/index.js
packages/psychart/example/Plotting Data/src/index.js
packages/psychart/package.json
packages/psychart/src/defaults.ts
packages/psychart/src/psychart.ts
packages/psychart/src/psystate.ts
packages/psychart/src/test.ts
packages/psychart/src/types.ts

Psychart cleanup

---

.github/workflows/ci.yml
.github/workflows/publish.yml
packages/dimensional/CHANGELOG.md
packages/dimensional/package.json

dimensional v1.0.1

---

typedoc.json

I GOT MY PREFERRED YOUTUBE HANDLE!!

Fix YouTube handle
